version: '3'

services:
  database:
    image: mysql/mysql-server:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-park_top}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeMe}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: ~
